name: LintTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lintTest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm ci --prefix mate-scripts
      - run: npm run lint
      - run: npm test
